name: Sync

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'yanglbme/gitee-pages-action'
    steps:
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          source-repo: git@github.com:yanglbme/gitee-pages-action.git
          destination-repo: git@gitee.com:yanglbme/gitee-pages-action.git